### PR TITLE
Pause monitoring

### PR DESCRIPTION
**Pull request by jwallet**
- to enable more options I removed the alert "show more"
- added option to "pause" the network monitoring and "resume" it.

### CODE REVIEW

**Comment by alexbrazier** [comment]
I like the pause option, but is it not still possible to use the `Alert` for it? At some point I was thinking of cleaning it up to look more like this so there could be more options next to the search bar and maybe eventually switching to an ActionSheet or Modal.

image

This option seems to limit us to 3 options like the Alert on Android as any more would cause it to go onto more lines 
image

**Comment by jwallet** [comment]
You are totally right

**Comment by jwallet** [comment]
options moved to a modal

**Review by alexbrazier — APPROVED** [review]
Looks good but seems there are some merge conflicts to resolve

**Pull request merged**
