### PR TITLE
Added Export all option to the More modal

### LINKED ISSUE #27: Export all Logs
**Feature Request**

Having the ability to export the full list of logged request to a JSON file stored locally on the device.

I know the project right now doesn't have any dependencies (that's really nice), but the easiest and most practical way to do it would include using a package like `react-native-fs`.

**Additional context**

### PR DESCRIPTION
**Pull request by Spencer-Yoder**
- Added export all button on the more modal. 

closes #27

### CODE REVIEW

**Comment by alexbrazier** [comment]
I started working on a draft of this a couple of days ago, but didn't get round to finishing it. I was thinking of exporting the logs in a HAR format so they can then be imported and read by other applications such as chrome. I pushed up my current change [here](https://github.com/alexbrazier/react-native-network-logger/compare/export-har), what do you think?

**Comment by Spencer-Yoder** [comment]
HAR format works for me! I didn't know if you wanted it formatted or not, so I was going to write a script to convert it.

**Comment by Spencer-Yoder** [comment]
> I started working on a draft of this a couple of days ago, but didn't get round to finishing it. I was thinking of exporting the logs in a HAR format so they can then be imported and read by other applications such as chrome. I pushed up my current change here, what do you think?

Would you also change the individual export to be in the har format too?

**Comment by alexbrazier** [comment]
> Would you also change the individual export to be in the har format too?

Yeah, I think that would make sense

**Comment by alexbrazier** [comment]
Thanks again for the PR, I've now merged #36 to export as a HAR format so I'll close this PR as that should cover it.

**Pull request closed without merging**
